### ISSUE TITLE
server.js crashes when a player tries to join

### ISSUE THREAD

**Issue by 4kh00** [kgurchiek/n-gon-multiplayer#5]
This is on the race branch. 
```
ubuntu@instance-20240312-1616:~$` node app.js
received: <Buffer 01 6a>
/home/ubuntu/app.js:59
        console.log(session.ws.readyState, session.ws2.readyState)
                            ^

TypeError: Cannot read property 'ws' of undefined
    at WebSocket.<anonymous> (/home/ubuntu/app.js:59:29)
    at WebSocket.emit (events.js:326:22)
    at WebSocket.emitClose (/usr/share/nodejs/ws/lib/websocket.js:257:10)
    at Socket.socketOnClose (/usr/share/nodejs/ws/lib/websocket.js:1217:15)
    at Socket.emit (events.js:314:20)
    at TCP.<anonymous> (net.js:676:12)
```
Note: app.js is server.js, but the port has been changed to 7000 to avoid conflicts wile other system services. The other js files have been unchanged (except for replacing the wss url). app.js is below:
```
const { WebSocketServer } = require('ws');

const sessions = {};

function genID() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let id = '';
    for (let i = 0; i < 8; i++) id += chars[Math.floor(Math.random() * chars.length)];
    return id
}

const wss = new WebSocketServer({
    port: 7000,
})

wss.on('connection', (ws) => {
    let state = 0;
    let session;

    ws.on('error', console.error);

    ws.on('message', (data) => {
        console.log('received:', data);
        const id = data[0];
        data = data.subarray(1);
        if (id == 0) {
            if (state == 0) {
                const id = genID();
                sessions[id] = { ws, offer: data };
                session = sessions[id];
                ws.send(`\x00${id}`);
                state++;
            } else if (state == 1) session.ws2.send(`\x01${data}`);
        } else if (id == 1) {
            if (state == 0) {
                session = sessions[data.toString()];
                if (session == null) {
                    ws.send('\x02Session not found');
                    ws.close();
                    return;
                }
                session.ws2 = ws;
                ws.send(`\x00${session.offer}`);
                state++;
            } else if (state == 1) {
                session.ws.send(`\x00${data}`);
                state++;
            } else if (state == 2) {
                session.ws.send(`\x01${data}`);
            }
        } else {
            ws.send('\x02Invalid role id');
            ws.close();
            return;
        }
    });

    ws.on('close', () => {
        console.log(session.ws.readyState, session.ws2.readyState)
        if (session.ws.readyState == 1) session.ws.close();
        if (session.ws2.readyState == 1) session.ws2.close();
        delete sessions[session];
    });
});

```

**Comment by kgurchiek** [comment]
I forgot to update the race branche when this bug was fixed on the main branch, I'll fix that in a minute
